### ISSUE TITLE
How to use for create an distribution.json

### ISSUE THREAD

**Issue by benjaminlecerf** [dscalzi/Nebula#1]
Hello i want to create a launcher from your source and i need yelp for create the distribution.json .
And how to use the Nebula soft ?
please thank you
(sorry for my bad english i am french)
my repo : https://github.com/bendev-fr/Launcher-L2

**Comment by dscalzi** [comment]
The project is not complete, hence why I havent posted instructions yet.

**Comment by TheCoolOne123** [comment]
Also, the repo is not forked! https://github.com/bendev-fr/Launcher-L2

**Comment by AzureZhen** [comment]
All the credits for dscalzi is still there. As long as you keep the credits, he's pretty good about the fork rule. I have a non forked version that he allows just fine.

**Comment by dscalzi** [comment]
I would prefer you at least preserve the commit history by cloning the main repo.

**Comment by TheCoolOne123** [comment]
^^^^ (That's why I forked it multiple times :P )

**Comment by dscalzi** [comment]
Command instructions are on the readme. Nebula still isnt done but you can use it for some basic things if you're really in need of it. Right now it can resolve the forge module for 1.7-1.12 and load top level mods/files. Submodules are not yet supported.

Follow the setup instructions on the README. You can generate a distribution in as few as three steps:

Tentative usage (exmple, docs are on README):
1. `npm run start -- i root` 
2. `npm run start -- g server <id> 1.7.10 --forge 10.13.4.1558`
3. `npm run start -- g distro`

**Comment by benjaminlecerf** [comment]
thank you dscalzi i can close the ticket now
