### ISSUE TITLE
Error with mod when I try to generate the distro

### ISSUE THREAD

**Issue by Superkooka** [dscalzi/Nebula#10]
I can't generate the distro. Nebula tell me that he have a TypeError. This error does not come from the mods because I tested with Optifine only and I have the same :/

Steps to reproduce:
1. ``git clone https://github.com/dscalzi/Nebula.git``
2. ``cd Nebula; npm i; npm run build``
3. ``echo "JAVA_EXECUTABLE=C:\Program Files (x86)\Java\jdk-14.0.1\bin\java.exe" "ROOT=D:\Launcher\Helios\Nebula\distro\infernia" "BASE_URL=http://cdn.superkooka.com/launcher/infernia"  > .env``
4. ``node dist/index.js init root``
5. ``node dist/index.js generate server infernia 1.14.4 --forge 28.2.17``
6. I put my file...
7. ``node dist/index.js generate distro``

Stack Trace:

![image](https://user-images.githubusercontent.com/35631093/83530357-ea190700-a4eb-11ea-8b51-fd2d9812d3be.png)

**Comment by dscalzi** [comment]
This is a bug with the mod, they have their Implementation-Version set to something completely invalid in the MANIFEST.MF. I downloaded the same mod, but version `1.6.5`, and it worked fine.
