### ISSUE TITLE
Issues with Linux 

### ISSUE THREAD

**Issue by RoxyBoxxy** [dscalzi/Nebula#12]
`npm run start generate server Test1 1.12.2 --forge 14.23.5.2847

> nebula@0.1.0 start /root/Nebula
> npm run build && node dist/index.js "generate" "server" "Test1" "1.12.2" "14.23.5.2847"

> nebula@0.1.0 build /root/Nebula
> npm run clean && npm run tsc

> nebula@0.1.0 clean /root/Nebula
> rimraf dist

> nebula@0.1.0 tsc /root/Nebula
> tsc

/root/Nebula/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/Nebula/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nebula@0.1.0 start: `npm run build && node dist/index.js "generate" "server" "Test1" "1.12.2" "14.23.5.2847"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nebula@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-04T21_44_22_908Z-debug.log`

my .env looks like this 
`
JAVA_EXECUTABLE=/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/bin/java
ROOT=/mnt/owo/packs
BASE_URL=http://erptime.ga/packs
`

**Comment by dscalzi** [comment]
Try with the latest commit

**Comment by RoxyBoxxy** [comment]
Thanks for the fast reply, i did i just cloned it today

**Comment by dscalzi** [comment]
I just pushed a commit

**Comment by RoxyBoxxy** [comment]
okay so i pulled the update see here 

`remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/dscalzi/Nebula
   0b063e4..2d8e5d1  master     -> origin/master
Updating 0b063e4..2d8e5d1
Fast-forward
 .vscode/launch.json                                          |   3 +-
 package-lock.json                                            |  31 +++-----
 package.json                                                 |   7 +-
 src/model/struct/model/module/file.struct.ts                 |   4 +-
 src/model/struct/model/module/forgemod/forgemod113.struct.ts | 163 +++++++++++++++++++++++----------------
 src/model/struct/model/module/forgemod/forgemod17.struct.ts  | 155 +++++++++++++++++++++----------------
 src/model/struct/model/module/library.struct.ts              |   4 +-
 src/model/struct/model/module/litemod.struct.ts              |  66 +++++++++++-----
 src/model/struct/model/module/module.struct.ts               |   8 +-
 src/resolver/forge/adapter/ForgeGradle2.resolver.ts          |  23 ++----
 src/resolver/forge/adapter/ForgeGradle3.resolver.ts          |  25 ++----
 src/resolver/forge/forge.resolver.ts                         |  21 +++++
 12 files changed, 289 insertions(+), 221 deletions(-)
`


How ever i am still getting the same error could my .env be wrong ?

**Comment by dscalzi** [comment]
1. Make sure you also run `npm i` after cloning
2. What version of node are you using? Working fine for me on windows with the latest node v12

**Comment by RoxyBoxxy** [comment]
ahhh this might be my fault my servers version is v8 let me update it and let you know

**Comment by RoxyBoxxy** [comment]
okay so thats fixed how ever this is now happing 

` npm run start -- g distro

> nebula@0.1.0 start /root/Nebula
> npm run build && node dist/index.js "g" "distro"


> nebula@0.1.0 build /root/Nebula
> npm run clean && npm run tsc


> nebula@0.1.0 clean /root/Nebula
> rimraf dist


> nebula@0.1.0 tsc /root/Nebula
> tsc

[2020-06-05 12:07:47] [debug] [Index]: Root set to /mnt/owo/packs
[2020-06-05 12:07:47] [debug] [Index]: Base Url set to http://erptime.ga/packs
[2020-06-05 12:07:47] [debug] [Index]: Invoked generate distro name distribution.json.
[2020-06-05 12:07:47] [warn] [ServerStructure]: No icon file found for server Test3-1.12.2.
[2020-06-05 12:07:47] [error] [Index]: Failed to generate distribution with root /mnt/owo/packs.
Error: ENOENT: no such file or directory, open '/mnt/owo/packs/servers/Test3-1.12.2/servermeta.json'`


Sorry about all the comments

**Comment by dscalzi** [comment]
Delete the server folder and regenerate it. Earlier bug probably messed it up.

**Comment by RoxyBoxxy** [comment]
okay so i did thats and its still trowing errors 

`[2020-06-04 11:19:49] [debug] [Index]: Root set to D:\TestRoot2
[2020-06-04 11:19:49] [debug] [Index]: Base Url set to http://localhost:8080/
[2020-06-04 11:19:49] [debug] [Index]: Invoked generate distro name distribution.json.
[2020-06-04 11:19:49] [warn] [ServerStructure]: No icon file found for server Test1-1.12.2.
[2020-06-04 11:19:49] [error] [Index]: Failed to generate distribution with root D:\TestRoot2.
Error: ENOENT: no such file or directory, open 'D:\TestRoot2\servers\Test1-1.12.2\servermeta.json'`

I also tried it on windows and still the same issue

**Comment by dscalzi** [comment]
Try running it with the dashes

`npm run start -- g server Test1 1.12.2 --forge 14.23.5.2847`

**Comment by RoxyBoxxy** [comment]
Oh wow i am stupid thanks worked fine haha thanks
