### ISSUE TITLE
Incapable of Downloading Forge

### ISSUE THREAD

**Issue by ReburonMaxus98** [dscalzi/Nebula#14]
as the title says im incapable of setting up proper forge version for the distribution i tried 
 npm run start generate server TestName 1.7.10 --forge 10.13.4.1614
 npm run start generate server  TestName 1.7.10 --forge latest 
n both had the same output:
-----------------------------------------------------------
> nebula@0.1.0 start C:\Users\MyUserName\Desktop\development\rootfolder
> npm run build && node dist/index.js "generate" "server" "TestName" "1.7.10" "10.13.4.1614"

> nebula@0.1.0 build C:\Users\MyUserName\Desktop\development\rootfolder
> npm run clean && tsc

> nebula@0.1.0 cleanC:\Users\MyUserName\Desktop\development\rootfolder
> rimraf dist

[2020-07-08 03:34:55] [debug] [Index]: Root set to C:\Users\MyUserName\Desktop\development\rootfolder
[2020-07-08 03:34:55] [debug] [Index]: Generating server TestName for Minecraft 1.7.10.
        ├ Forge version: null
        └ LiteLoader version: null
-------------------------------------
i looked into the src folder in case i could find why is this happening and saw the "forge.resolver.ts" file so i looked into it and discovered this part of code that might do problem atleast in the npm run start generate server TestName 1.7.10 --forge 10.13.4.1614 phase 
-------------------------------
   // Coverage is not 100% but that doesnt matter.
    // It's enough and you should always use the latest version anyway.
    public inferArtifactVersion(): string {
        const version = `${this.minecraftVersion}-${this.forgeVersion}`

        const ver = this.forgeVersion.split('.')
        const major = Number(ver[0])
        if ([12, 11, 10].indexOf(major) > -1) {
            const minor = Number(ver[1])
            const revision = Number(ver[2])
            const extra = Number(ver[3])

            if (major === 10) {
                if (minor === 13 && revision >= 2 && extra >= 1300) {
                    return `${version}-1.7.10`
                }
-------------------------------
as with the version not fitting into the filter i changed it to:
-------------------------------
  // It's enough and you should always use the latest version anyway.
    public inferArtifactVersion(): string {
        const version = `${this.minecraftVersion}-${this.forgeVersion}`

        const ver = this.forgeVersion.split('.')
        const major = Number(ver[0])
        if ([12, 11, 10].indexOf(major) > -1) {
            const minor = Number(ver[1])
            const revision = Number(ver[2])
            const extra = Number(ver[3])

            if (major === 10) {
                if (minor === 13 && revision >= 5 && extra >= 1714) {
                    return `${version}-1.7.10`
                }
-------------------------------
yet it seems there wasnt problem at all which i shouldve expected wwith this part of code propably handling only custom versions entered but i didnt found anything else i was capable of understanding enough to edit it so im asking here for support

**Comment by dscalzi** [comment]
Read the readme. https://github.com/dscalzi/Nebula#command-usage

```
npm run start -- generate server TestName 1.7.10 --forge latest
```
