### ISSUE TITLE
Error while adding Hypixel to my distro

### ISSUE THREAD

**Issue by splatboy20081** [dscalzi/Nebula#18]
![image](https://user-images.githubusercontent.com/64037464/98051705-49f04280-1de9-11eb-8cf9-27f1ce28cb4e.png)

**Comment by splatboy20081** [comment]
`npm run start generate server Hypixel 1.8.9`

**Comment by splatboy20081** [comment]
Java 11, OpenJDK JRE. Is it meant to be the JDK?

**Comment by dscalzi** [comment]
Vanilla is not supported at this time, select a forge version when generating a server and add no mods.

**Comment by dscalzi** [comment]
Additionally, please upgrade to Node 14. Node 12 is no longer supported by Nebula.
