### ISSUE TITLE
Whee, a distro error now!

### ISSUE THREAD

**Issue by splatboy20081** [dscalzi/Nebula#19]
NodeJS Version: v14.15.0

I probably seem like an idiot or something now...
![image](https://user-images.githubusercontent.com/64037464/98185430-75def700-1ec1-11eb-8d0e-19e6620eed96.png)

**Comment by dscalzi** [comment]
Read the readme.

`npm run start -- g distro`

**Comment by splatboy20081** [comment]
oh x)

**Comment by splatboy20081** [comment]
that doesn't work either

**Comment by TheFlash787** [comment]
You need to make sure that you `.env` file is setup correctly.

Make sure that you have a file **called** `.env` inside of your Nebula root directory and that it contains the details as mentioned in the readme.

**Comment by splatboy20081** [comment]
My file is in C:\Users\me\.env, does it go in the Nebula folder

Nebula is C:\Users\me\Nebula

**Comment by splatboy20081** [comment]
aight thx it works

**Comment by TheFlash787** [comment]
> 
> 
> My file is in C:\Users\me.env, does it go in the Nebula folder
> 
> Nebula is C:\Users\me\Nebula

It needs to go into `C:\Users\me\Nebula`
Your file must be named `.env` not `hello.env` or `me.env` - You should be able just to name it `.env`.

> 
> 
> aight thx it works

Great!
