### ISSUE TITLE
No way to delete servers?

### ISSUE THREAD

**Issue by splatboy20081** [dscalzi/Nebula#20]

**Comment by dscalzi** [comment]
delete the folder?

**Comment by splatboy20081** [comment]
the Nebula folder? k

**Comment by TheFlash787** [comment]
If you can write more indepth issues, we might be able to help you further. However it might be better if you were to join the Discord server so that we can guide you through things in real-time, if you're having issues.

https://discord.gg/CZTJTeyDgm

**Comment by splatboy20081** [comment]
![image](https://user-images.githubusercontent.com/64037464/98311007-31b42b00-1f83-11eb-9736-7d580f01980b.png)

**Comment by splatboy20081** [comment]
irony

**Comment by splatboy20081** [comment]
also whoever can, delete the issue

**Comment by GeekCornerGH** [comment]
You cannt
