### ISSUE TITLE
Failed to generate distribution with root...  Error: Bad archive

### ISSUE THREAD

**Issue by nathanaaron** [dscalzi/Nebula#26]
I'm receiving an error after generating the distribution.

**.env file:
JAVA_EXECUTABLE=C:\Program Files\AdoptOpenJDK\jdk-8.0.282.8-hotspot\bin\java.exe
ROOT=d:\nebula-repo
BASE_URL=http://localhost:8080/
HELIOS_DATA_FOLDER=C:\Users\Nathan\AppData\Roaming\Helios Launcher**

Commands run:

**npm run start -- init root
npm run start -- generate server MaddLads-1.16.5_Forge 1.16.5 --forge latest
*- moved required files to root directory -*
npm run start -- generate distro MadLads_distribution --installLocal**

I'm able to install the forge client, and the distribution generation appears to start correctly and finds the plugins - however after a few seconds, it eventually errors out with the following:

**[2021-04-06 15:36:44] [error] [Index]: Failed to generate distribution with root d:\nebula-repo. 
Error: Bad archive
    at FsRead.readUntilFoundCallback [as callback] (C:\Users\Nathan\Documents\GitHub\Nebula\node_modules\node-stream-zip\node_stream_zip.js:202:39)
    at FsRead.readCallback (C:\Users\Nathan\Documents\GitHub\Nebula\node_modules\node-stream-zip\node_stream_zip.js:992:25)
    at FSReqCallback.wrapper [as oncomplete] (fs.js:539:5)**

I've tried to clear the directory and restart the install, but keep running into the same issue. Any idea what might be occurring? Or if I'm doing something incorrect?

**Comment by dscalzi** [comment]
what do you mean `- moved required files to root directory -`

**Comment by nathanaaron** [comment]
> what do you mean `- moved required files to root directory -`

I moved the forge mods to their respective folders - optionaloff, optionalon, required

**Comment by nathanaaron** [comment]
I excluded the mods from those directories and the distribution is generating fine now. Are forgemods not supposed to be added to the distribution in this manner? Apologies if I'm interpreting something wrong.

**Comment by nathanaaron** [comment]
Wound up being a mod that wasn't pulling correctly, was able to remove it and this is working now!
