### ISSUE TITLE
Error while generating distribution 

### ISSUE THREAD

**Issue by LaxoLP** [dscalzi/Nebula#29]
So I have done everything but this keeps happen: 
[2021-05-18 09:39:51] [error] [Index]: Failed to generate distribution with root D:\NebulaSetup\Nebula.
Error: ENOENT: no such file or directory, open 'D:\NebulaSetup\Nebula\cache\forge\1.16.5-36.1.23\versions\1.16.5-forge-36.1.23\1.16.5-forge-36.1.23.json

**Comment by dscalzi** [comment]
Indicated that this is resolved on discord.
