### ISSUE TITLE
Nebula distribution.json data validation issue

### ISSUE THREAD

**Issue by dwightdurmon** [dscalzi/Nebula#32]
Hello and thanks for reading this ticket!

I ran into an issue where a mod has an improperly formatted `/META-INF/MANAFEST.MF` file.  The file looks like this:

```
Manifest-Version: 1.0
Specification-Title: sophisticatedbackpacks
Specification-Vendor: p3pp3rf1y
Specification-Version: 1
Implementation-Title: SophisticatedBackpacks
Implementation-Version: property(class java.lang.String, provider(?))
Implementation-Vendor: p3pp3rf1y
Implementation-Timestamp: 2021-06-04T22:11:18+0000
```

When I run Nebula to generate the distribution.json, I get an id entry for the mod that looks like this:

`"id": "net.p3pp3rf1y:sophisticatedbackpacks:property(class java.lang.String, provider(?))@jar",`

which causes the client to fail to launch.  To correct the issue, I have to update the entry to an actual version... like this.

` "id": "net.p3pp3rf1y:sophisticatedbackpacks:1.16.4-2.5.0.271@jar",`

I don't know if it is possible either in this version or version 2.0 to add a check.  It would be nice if Nebula could do some validation on the input and maybe replace the invalid characters or use the version on the filename or even set it to something like 1.x-unknown so that the distribution.json will parse correctly on the client.

**Comment by dscalzi** [comment]
This is a bug with the mod, their build script is failing to put a version into the manifest. Nebula cannot account for every mistake mod authors make. Please file an issue with them to fix their manifest.

**Comment by dwightdurmon** [comment]
Totally agree and understand. I did open a ticket for the mod in question to fix the issue on their end, so hopefully they will address that.  At the very least, hopefully this will be helpful information for anyone who encounters a similar issue.  Thanks for the quick response and have a great weekend.  :-)
