### ISSUE TITLE
Error generating distro

### ISSUE THREAD

**Issue by PanaNotFound** [dscalzi/Nebula#33]
Hello good Morning
Sorry for my not so professional English
but I come to see if you could help me with a problem that I have when trying to generate the distro, I do all the steps well and I don't know what is wrong
It would be helpful if you could help me: D
![Desktop Screenshot 2021 07 15 - 13 06 58 66](https://user-images.githubusercontent.com/82159790/125829319-202b4644-bca1-4e26-8a41-6106a5ab2811.png)

**Comment by dscalzi** [comment]
Something might be wrong in your cache. Try running with `--invalidateCache` to generate a fresh one. Please make sure you set the installer directory to the cache folder that it prints in the log.

**Comment by PanaNotFound** [comment]
Hello how are you doing
Here I again try to do what you told me and I get the same thing plus another error I also saw that when I do not put anything, no mod or config generates the distro well but when I put a config or mods it gives me the errors: /
I don't know if there is a solution but if there is, it would help me a lot
![Desktop Screenshot 2021 07 26 - 13 24 02 75 (2)](https://user-images.githubusercontent.com/82159790/127032587-9178be3e-e791-449f-af47-449d2e565136.png)

**Comment by dscalzi** [comment]
Your java esecutable does not exist. Please make sure the .env points to a java installation that exists.
