### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by Username128233** [dscalzi/Nebula#34]
Hello, very good, I come to ask a little thing that I do not know why it has been happening to me and it has been 3 weeks and I do not know how to solve it, The problem is that when trying to start the launcher it stays at 100% and does not start the minecraft it would be great help if there was a solution for my problem :D

**Comment by zendrique** [comment]
Hello, I have the same problem, but it gets stuck at 99%. Personally, to correct the problem I restart the launcher
