### ISSUE TITLE
Weird error message when compiling 1.16 modpacks

### ISSUE THREAD

**Issue by SirOMGitsYOU** [dscalzi/Nebula#35]
Hey Getting this weird error message on 1.16 mods,

https://hastebin.com/tesidiyagi.swift

I can sometimes get it to move to the next mod by changing the name or removing any numbers but it is quite tedious to do this for all mods.

**Comment by lilRufi** [comment]
Same error here

**Comment by dscalzi** [comment]
Please ping me (@dscalzi) if I havent looked at this by mid next week.

**Comment by dscalzi** [comment]
I'm not able to reproduce this. Can you zip your forgemods folder and send it to me? @SirOMGitsYOU

**Comment by SirOMGitsYOU** [comment]
> I'm not able to reproduce this. Can you zip your forge mods folder and send it to me? @SirOMGitsYOU

Yep, of course, this is the folder I used in the original log report
https://transfer.sh/RQVa8s/forgemods.zip

This is the same modpack, just updated everything and added back all the mods I had removed to try to diagnose this issue.
https://transfer.sh/JxXaj6/forgemods.zip

**Comment by dscalzi** [comment]
confirmed the problem, investigating a fix

**Comment by dscalzi** [comment]
Should be resolved, thank you for the report.

**Comment by SirOMGitsYOU** [comment]
> Should be resolved, thank you for the report.

Getting this error message when generating distro new with a fresh server generated on the newest

https://hastebin.com/mohogatage.css

**Comment by dscalzi** [comment]
I didn't push it to master, my mistake. Try now
