### ISSUE TITLE
add icon on servermeta.json

### ISSUE THREAD

**Issue by ninjidufroid** [dscalzi/Nebula#44]
Hi! Please, can you add a icon value in schema auto configuration in servermeta.json ? Thanks you ❤️

**Comment by dscalzi** [comment]
not sure what the request here is? Specifying the icon in the servermeta vs just putting the file in the root?

**Comment by Raft08** [comment]
Someone has made a pull request for this: #39

**Comment by dscalzi** [comment]
Supported as of https://github.com/dscalzi/Nebula/commit/1a537e33f4d4843d0896259edd6d1f2f859e7d78

See https://github.com/dscalzi/Nebula#setting-the-server-icon

Remember, to regenerate the schemas just do `npm run start -- g schemas`
