### ISSUE TITLE
Forge version: null

### ISSUE THREAD

**Issue by rayzens1** [dscalzi/Nebula#52]
When i `npm start -- generate server pokeuniversesurvie 1.16.5 --forge 36.2.29`

The console return me:

[2023-01-11 15:35:12] [debug] [Index]: Root set to C:\pokeuniverse
[2023-01-11 15:35:12] [debug] [Index]: Generating server pokeuniversesurvie for Minecraft 1.16.5. 
        └ Forge version: null
        
My .env file:

JAVA_EXECUTABLE=C:\Program Files\Eclipse Adoptium\jdk-8.0.352.8-hotspot\bin\java.exe
ROOT=C:\pokeuniverse
BASE_URL=http://pokeuniverse.wstr.fr/
HELIOS_DATA_FOLDER=C:\Users\utilisateur\AppData\Roaming\Helios Launcher

I don't get any forge windows.

I have put any version of forge 1.16.5 and do the same error.

**Comment by dscalzi** [comment]
I'm not getting the same issue, are you up to date with master?

**Comment by rayzens1** [comment]
i have a new version of NPM.

If use NPM v9.1.2 use `node dist/index.js g server [nom du serveur] [Version de Minecraft ex 1.12.2] --forge [Version de Forge ex 14.23.5.2859]` instead `npm start -- generate server [nom du serveur] [Version de Minecraft ex 1.12.2] --forge [Version de Forge ex 14.23.5.2859]`

**Comment by dscalzi** [comment]
From discord (incase anyone else has this issue):

Something is wrong with your cli, the --forge argument is not correctly getting passed to the npm command.

Try `node dist/index.js g server pokeuniverse 1.16.5 --forge 36.2.34`
