### ISSUE TITLE
Helios Launcher .exe return default helios launcher when launch.

### ISSUE THREAD

**Issue by rayzens1** [dscalzi/Nebula#54]
I have put mod in Helios Launcher, i just translate all message in setting page.

I have generate the distribution.json and i put all file on my webhost.

I have build the .exe launcher.

I launch the exe, this install me all file and put me a short cut on my desktop. When i click for the first time on, it launch the launcher. After a short moment, the shortcut come white (like the shortcut is deleted), and the default icon repop i click on and give me the default HeliosLauncher

This is the video : https://www.youtube.com/watch?v=wnlDZHyBuF4

**Comment by karu724** [comment]
This is because "Auto-Update". Please change 'Url' in package.json

**Comment by TheRayZens** [comment]
Yes is come from GitHub Link. I just have to fork and give release.

**Comment by dscalzi** [comment]
Update the urls in the launcher package.json, as well as in the updater code. Search for dscalzi and you'll probably be able to find it.
