### ISSUE TITLE
Error on Distro Generation

### ISSUE THREAD

**Issue by tommyjcode** [dscalzi/Nebula#6]
The following link logs the issue.

https://paste.ubuntu.com/p/PCDxf5GfZ4/

It's probably me being stupid, but the Forge installer isn't launching either.

**Comment by dscalzi** [comment]
Did you set the java executable in the `.env`?

**Comment by tommyjcode** [comment]
I had set it all with
export JAVA_EXECUTABLE=____
I learned today you can use
touch .env
to make an .env file on Mac! Thanks!
