### ISSUE TITLE
Missing forge-version.json file

### ISSUE THREAD

**Issue by jakeau** [dscalzi/Nebula#7]
`sudo node dist/index.js generate distro
Root set to /var/www/mc.doamin.com/nebula/Nebula
Base Url set to http://nebula/Nebula
Invoked generate distro name distribution.json.
No icon file found for server 114domain-1.14.4.
Checking for forge installer at /var/www/mc.doamin.com/nebula/Nebula/repo/lib/net/minecraftforge/forge/1.14.4-28.2.0/forge-1.14.4-28.2.0-installer.jar..
Using locally discovered forge installer.
Beginning processing of Forge v28.2.0 (Minecraft 1.14.4)
Spawning forge installer
============== [ IMPORTANT ] ==============
When the installer opens please set the client installation directory to:
/var/www/mc.doamin.com/nebula/Nebula/work
===========================================
[Forge Installer] JVM info: Private Build - 1.8.0_242 - 25.242-b08
[Forge Installer] java.net.preferIPv4Stack=true
[Forge Installer] Found java version 1.8.0_242
[Forge Installer] Exception in thread "main"
[Forge Installer] java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
[Forge Installer] at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807)
[Forge Installer] at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
[Forge Installer] at javax.swing.UIManager.getSystemLookAndFeelClassName(UIManager.java:611)
[Forge Installer] at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:162)
[Forge Installer] at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:143)
[Forge Installer] Exited with code 1
Installer finished, beginning processing.
Processing Version Manifest
Failed to generate distribution with root /var/www/mc.doamin.com/nebula/Nebula. { Error: ENOENT: no such file or directory, open '/var/www/mc.doamin.com/nebula/Nebula/work/versions/1.14.4-forge-28.2.0/1.14.4-forge-28.2.0.json'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/www/mc.doamin.com/nebula/Nebula/work/versions/1.14.4-forge-28.2.0/1.14.4-forge-28.2.0.json' }
`

Whenever running 'sudo node dist/index.js generate distro' if I create the .json file then rerun the command it deleted the /versions folder. Any advice on how to do this, cheers!
Also awesome job on the client.

**Comment by dscalzi** [comment]
Are you running this on a headless machine?

```
[Forge Installer] java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
[Forge Installer] Exited with code 1
```

The forge installer is GUI based and cannot be run on a headless machine. See #5

**Comment by jakeau** [comment]
Cheers, 
My apologies for your time

**Comment by jakeau** [comment]
Do you have any advice on how to obtain the forge submodules manually? 
Such as:
`                        {
                            "id": "net.minecraft:launchwrapper:1.12",
                            "name": "Mojang (LaunchWrapper)",
                            "type": "Library",
                            "artifact": {
                                "size": 32999,
                                "MD5": "934b2d91c7c5be4a49577c9e6b40e8da",
                                "url": "http://mc.westeroscraft.com/WesterosCraftLauncher/files/1.12.2/launchwrapper-1.12.jar"
                            }
                        },
`

**Comment by dscalzi** [comment]
For 1.12.2 and below just check forge's version.json. For 1.13+ it's more complicated. You need to pay attention to what the installer generates and what forge is looking for at runtime.
