### ISSUE TITLE
How to fix this problem

### ISSUE THREAD

**Issue by ddoiy1** [dscalzi/Nebula#71]
![스크린샷 2024-05-31 003242](https://github.com/dscalzi/Nebula/assets/90036352/394d9699-2eb1-4b6e-833a-28668a305b3c)

When I ran the npm start -- int root command, only the following output was displayed:

> nebula@0.1.0 start
> npm run build && node dist/index.js int root

> nebula@0.1.0 build
> npm run clean && npm run tsc

> nebula@0.1.0 clean
> rimraf dist

> nebula@0.1.0 tsc
> tsc

Then, after generating the server files, I encountered an issue when running the npm start -- generate distro command.

**Comment by Ulysse2211** [comment]
Make a server first before generating the distro.

**Comment by ddoiy1** [comment]
After creating the server, I ran npm start -- generate distro.
