### ISSUE TITLE
404 for librairies with old Minecraft version

### ISSUE THREAD

**Issue by Superkooka** [dscalzi/Nebula#9]
I know it has nothing to do with Nebula but older versions of Minecraft (1.7.2 for example) have libraries that are no longer available on https://librairies.minecraft.net. (https://libraries.minecraft.net/org/apache/logging/log4j/log4j-api/2.0/log4j-api-2.0-beta.jar)

Steps to reproduce:
1. ``git clone https://github.com/dscalzi/Nebula.git``
2. ``cd Nebula; npm i; npm run build``
3. ``echo "JAVA_EXECUTABLE=C:\Program Files (x86)\Java\jdk-14.0.1\bin\java.exe" "ROOT=D:\Launcher\Helios\Nebula\distro\infernia" "BASE_URL=http://cdn.superkooka.com/launcher/citysmine"  > .env``
4. ``node dist/index.js init root``
5. ``node dist/index.js generate server citysmine 1.7.2 --forge 10.12.2.1121``
6. I put my file...
7. ``node dist/index.js generate distro``

Stack Trace:

```
A 404 error with the librairies by Axios (from https://libraries.minecraft.net/org/apache/logging/log4j/log4j-api/2.0/log4j-api-2.0-beta.jar)
```

**Comment by GeekCornerGH** [comment]
1.7.2 is not supported by Nebula.

**Comment by dscalzi** [comment]
Why do you need 1.7.2 and not 1.7.10?

**Comment by Superkooka** [comment]
Because I use a Modpack in 1.7.10

**Comment by GeekCornerGH** [comment]
Mods in 1.7.2 are working in 1.7.10.
So you can use Nebula to generate a 1.7.10 distribution.json

**Comment by Superkooka** [comment]
@GeekCornerGH and if the server run in 1.7.10 it's good too ?

**Comment by GeekCornerGH** [comment]
> @GeekCornerGH and if the server run in 1.7.10 it's good too ?

@Superkooka Yes

**Comment by dscalzi** [comment]
Is this resolved?

**Comment by Superkooka** [comment]
Yes, thank you
